Removed OS and architecture check from scripts/common.  Successful test on ubuntu-20.04-x86_64 and raspbian-11-aarch64.

diff --git a/scripts/common b/scripts/common
--- a/scripts/common
+++ b/scripts/common
@@ -25,18 +25,28 @@ InstallPackages()
         return 0
     fi
 
+    # Check if running as root
+    if [ ${EUID} -eq 0 ]; then
+        # Running as root, sudo is not available.
+        SUDO=""
+    else
+        # Running as a user, sudo is required.
+        SUDO="sudo"
+    fi
+
+    UPDATE_COMMAND="${SUDO} apt update"
+    INSTALL_COMMAND="${SUDO} apt install -y --no-install-recommends ${@}"
+
     echo "${UPDATE_COMMAND}"
     ${UPDATE_COMMAND}
 
-    for PACKAGE in "${@}"; do 
-        echo "${INSTALL_COMMAND} ${PACKAGE}"
-        ${INSTALL_COMMAND} ${PACKAGE}
+    echo "${INSTALL_COMMAND}"
+    ${INSTALL_COMMAND}
 
-        # Check if install failed
-        if [ $? -ne 0 ]; then 
-            exit 1
-        fi
-    done
+    # Check if install failed
+    if [ $? -ne 0 ]; then 
+        exit 1
+    fi
 }
 
 GitClone()
@@ -95,6 +105,7 @@ BuildAndInstall()
         fi
     fi
 
+    NUMBER_OF_CORES=$(grep -c processor /proc/cpuinfo)
     CMAKE_CONFIGURE="cmake -H${SOURCE_PATH} -B${BUILD_PATH} ${CMAKE_FLAGS}"
     CMAKE_BUILD_INSTALL="cmake --build ${BUILD_PATH} --target install -j ${NUMBER_OF_CORES}"
 
@@ -113,72 +124,10 @@ BuildAndInstall()
     fi
 }
 
-CheckSystem()
-{
-    if [[ ${OSTYPE} == linux-gnu* ]]; then
-        # Linux
-        OS_NAME="linux"
-
-        # Check architecture
-        ARCHITECTURE=$(uname -m)
-        if [[ ${ARCHITECTURE} == x86_64 ]]; then
-            # x86_64
-            :
-        elif [[ ${ARCHITECTURE} == armv7l ]]; then
-            # ARM 32-bit
-            :
-        elif [[ ${ARCHITECTURE} == aarch64 ]]; then
-            # ARM 64-bit
-            :
-        else
-            # Unsuported architecture.
-            echo "The architecture ${ARCHITECTURE} is not supported."
-            exit 1
-        fi
-
-        NUMBER_OF_CORES=$(grep -c processor /proc/cpuinfo)
-
-        if grep -q 'ubuntu' /etc/os-release; then
-            OS_VERSION=$(grep -oP 'VERSION_ID="\K[^"]+' /etc/os-release)
-            OS_NAME="ubuntu-${OS_VERSION}"
-            
-        elif grep -q 'buster' /etc/os-release; then
-            # Raspberry Pi buster.  Only use one core.
-            OS_NAME="raspbian-10"
-        elif grep -q 'bullseye' /etc/os-release; then
-            # Raspberry Pi bullseye.  Only use one core.
-            OS_NAME="raspbian-11"
-        else
-            # Unsuported Raspberry Pi OS version.
-            echo "The Raspberry Pi OS version is not supported."
-            exit 1
-        fi
-
-        # Check if running as root
-        if [ ${EUID} -eq 0 ]; then
-            # Running as root, sudo is not available.
-            SUDO=""
-        else
-            # Running as a user, sudo is required.
-            SUDO="sudo"
-        fi
-
-        UPDATE_COMMAND="${SUDO} apt update"
-        INSTALL_COMMAND="${SUDO} apt install -y --no-install-recommends"
-    else
-        # Unsuported operating system.
-        echo "The operating system ${OSTYPE} is not supported."
-        exit 1
-    fi
-}
-
-# Check the OS and architecture
-CheckSystem
-
 # Set common source, build and install paths
 SCRIPT_PATH="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";
 COMMON_DEPENDENCIES_PATH="$(realpath ${SCRIPT_PATH}/../dependencies)"
-COMMON_SOURCE_PATH="${COMMON_DEPENDENCIES_PATH}/source"
-COMMON_BUILD_PATH="${COMMON_DEPENDENCIES_PATH}/build"
-COMMON_INSTALL_PATH="${COMMON_DEPENDENCIES_PATH}/${OS_NAME}/${ARCHITECTURE}"
+COMMON_SOURCE_PATH=${COMMON_DEPENDENCIES_PATH}/source
+COMMON_BUILD_PATH=${COMMON_DEPENDENCIES_PATH}/build
+COMMON_INSTALL_PATH=${COMMON_DEPENDENCIES_PATH}/install
 COMMON_REQUIRED_PACKAGES="gcc g++ make cmake git ca-certificates"
